# Nombre del Workflow

name: Cobertura de Test

# Eventos que ejecutan nuestro Workflow. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ development ]
    types: [closed]

# Un Workflow esta conformado por jobs, en nuestro caso tenemos un único job llamado cobertura
jobs:
  # Nombre de nuestro único Job
  cobertura:
    # Configuramos el SO de la maquina vitual ( se pueden setear otros, inclusive varios al mismo tiempo)
    runs-on: ubuntu-latest

    # Los jobs estan conformados por pasos o secuencias de ejecución. Podemos usar actions predefinidos o mismo ejecutar comandos de consola
    steps:
    - name: Hacer Checkout Repo
      uses: actions/checkout@v2

    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
            
    - name: Compilar y Correr Test con Maven
      run: mvn -B test

    - name: Generar JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2.0.1

    - name: Hacer Commit del badge (si cambió)
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'Github'
          git config --global user.email 'YOUR-GITHUB-USERID@users.noreply.github.com'
          git add -A
          git commit -m "Autogeneración JaCoCo coverage badge"
          git push
        fi
        
    - name: Upload Reporte JaCoCo
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/
